apiVersion: batch/v1
kind: Job
metadata:
  name: send-categories
spec:
  completions: 1
  template:
    metadata:
      labels:
        app: send-categories
    spec:
      imagePullSecrets:
      - name: gitlab-auth
      containers:
      - command: ["python", "send_categories.py"]
        image: registry.gitlab.com/fevemania/shopee_side_project/send_categories:v0.0.2
        name: send-categories
      initContainers:
      - name: init-mysql
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup mysql; do echo waiting for msql; sleep 2; done;']
      - name: init-rabbitmq
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup rabbitmq; do echo waiting for rabbitmq; sleep 2; done;']
      restartPolicy: Never
  backoffLimit: 1
