version: '3.7'
services:
    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq:latest
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5672:5672"
        labels:
            NAME: "rabbitmq"
        volumes:
            - rabbitmq:/var/lib/rabbitmq
            - rabbitmq-logs:/var/log/rabbitmq

    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: 'mypass'
            MYSQL_ROOT_PASSWORD: 'mypass'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - "3306:3306"
        volumes:
            - mysql:/var/lib/mysql

    category_worker:
        build: .
        depends_on:
            - rabbitmq
       #links:
       #    - rabbitmq-server
        environment:
            RABBIT_HOST: rabbitmq
        command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "python", "-u", "category_worker.py"]

volumes:
    rabbitmq:
    rabbitmq-logs:
    mysql:
