version: '3'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        environment:
            - "discovery.type=single-node"
        ports:
            - 9200:9200
        expose:
            - 9200
        
    postgres:
        image: groonga/pgroonga:latest
        restart: always
        environment:
            - POSTGRES_MULTIPLE_DATABASES=shopee_db,admin|rakuten_db,admin|pinkoi_db,admin
            - POSTGRES_DB=postgres
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=mypass
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
            - './side_project/postgres_init_files:/docker-entrypoint-initdb.d'
    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - 5672:5672
        labels:
            NAME: rabbitmq
        volumes:
            - rabbitmq:/var/lib/rabbitmq
    redis:
        image: redis:alpine
        restart: always
        ports:
            - 6379:6379
        volumes:
            - redis:/data
    fluentd:
        build:
            context: . 
            dockerfile: ./side_project/fluentd/Dockerfile
        ports:
            - 9880:9880
        volumes:
            - fluentd:/fluentd/log
    restful_api_service:
        build:
            context: .
            dockerfile: ./side_project/restful_api/Dockerfile
        depends_on:
            - postgres
        environment:
            - POSTGRES_SHOPEE_DB=shopee_db
            - POSTGRES_RAKUTEN_DB=rakuten_db
            - POSTGRES_PINKOI_DB=pinkoi_db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=mypass
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - REDIS_HOST=redis
            - FLUENTD_HOST=fluentd
            - RABBITMQ_USER=admin
            - RABBITMQ_PASSWORD=mypass
            - RABBITMQ_HOST=rabbitmq
        command: ["./wait-for-it.sh", "-t", "30", "postgres:5432", "--", "/bin/bash", "flask_run.sh"]
        volumes:
            - './side_project/restful_api/shopee/migrations:/shopee/migrations'
            - './side_project/restful_api/pinkoi/migrations:/pinkoi/migrations'
            - './side_project/restful_api/rakuten/migrations:/rakuten/migrations'
        ports:
            - 5000:5000
#   # write new s3 data into postgres per helf hour.
#   write_s3_jsonfile_into_postgres_routine:
#       build:
#           context: .
#           dockerfile: ./side_project/write_s3_jsonfile_into_postgres_routine/Dockerfile
#       environment:
#           - POSTGRES_DB=shopee_db
#           - POSTGRES_USER=admin
#           - POSTGRES_PASSWORD=mypass
#           - POSTGRES_HOST=postgres
#           - POSTGRES_PORT=5432
#           - AWS_ACCESS_KEY_ID=AKIAJV2DQB4O6JV3O3XQ
#           - AWS_SECRET_ACCESS_KEY=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
#           - AWS_DEFAULT_REGION=ap-northeast-1
#       volumes:
#           - './side_project/write_s3_jsonfile_into_postgres_routine/log:/mnt/log'
#   shopee_category_crawler:
#       build:
#           context: .
#           dockerfile: ./side_project/crawler/shopee/category_crawler/Dockerfile
#       depends_on:
#           - postgres
#       environment:
#           - POSTGRES_DB=shopee_db
#           - POSTGRES_USER=admin
#           - POSTGRES_PASSWORD=mypass
#           - POSTGRES_HOST=postgres
#           - POSTGRES_PORT=5432
#       command: ["./wait-for-it.sh", "-t", "30", "rabbitmq:5672", "--", "python", "-u", "category_crawler.py"]
#   shopee_crawler_routine:
#       build:
#           context: .
#           dockerfile: ./side_project/crawler/shopee/crawler_routine/Dockerfile
#       environment:
#           - POSTGRES_DB=shopee_db
#           - POSTGRES_USER=admin
#           - POSTGRES_PASSWORD=mypass
#           - POSTGRES_HOST=postgres
#           - POSTGRES_PORT=5432  
#           - RABBITMQ_USER=admin
#           - RABBITMQ_PASSWORD=mypass
#           - RABBITMQ_HOST=rabbitmq
#   shopee_category_worker:
#       build:
#           context: .
#           dockerfile: ./side_project/crawler/shopee/category_worker/Dockerfile
#       depends_on:
#           - rabbitmq
#       environment:
#           - RABBITMQ_USER=admin
#           - RABBITMQ_PASSWORD=mypass
#           - RABBITMQ_HOST=rabbitmq
#           - REDIS_HOST=redis
#       command: ["./wait-for-it.sh", "-t", "30", "rabbitmq:5672", "--", "python", "-u", "category_worker.py"]
#   shopee_product_worker:
#       build:
#           context: .
#           dockerfile: ./side_project/crawler/shopee/product_worker/Dockerfile
#       deploy:
#           replicas: 8
#       depends_on:
#           - rabbitmq
#           - fluentd
#       environment:
#           - RABBITMQ_USER=admin
#           - RABBITMQ_PASSWORD=mypass
#           - RABBITMQ_HOST=rabbitmq
#           - REDIS_HOST=redis
#           - FLUENTD_HOST=fluentd
#       command: ["./wait-for-it.sh", "-t", "30", "rabbitmq:5672", "--", "python", "-u", "product_worker.py"]
#   rakuten_crawler_routine:
#       build:
#           context: .
#           dockerfile: ./side_project/crawler/rakuten/crawler_routine/Dockerfile
#       environment:
#           - POSTGRES_DB=rakuten_db
#           - POSTGRES_USER=admin
#           - POSTGRES_PASSWORD=mypass
#           - POSTGRES_HOST=postgres
#           - POSTGRES_PORT=5432  
#           - RABBITMQ_USER=admin
#           - RABBITMQ_PASSWORD=mypass
#           - RABBITMQ_HOST=rabbitmq
#   rakuten_category_worker:
#       build:
#           context: .
#           dockerfile: ./side_project/crawler/rakuten/category_worker/Dockerfile
#       deploy:
#           replicas: 8
#       depends_on:
#           - rabbitmq
#           - fluentd
#       environment:
#           - RABBITMQ_USER=admin
#           - RABBITMQ_PASSWORD=mypass
#           - RABBITMQ_HOST=rabbitmq
#           - REDIS_HOST=redis
#           - FLUENTD_HOST=fluentd
#       command: ["./wait-for-it.sh", "-t", "30", "rabbitmq:5672", "--", "python", "-u", "category_worker.py"]
#   rakuten_product_worker:
#       build:
#           context: .
#           dockerfile: ./side_project/crawler/rakuten/product_worker/Dockerfile
#       deploy:
#           replicas: 50
#       depends_on:
#           - rabbitmq
#           - fluentd
#       environment:
#           - RABBITMQ_USER=admin
#           - RABBITMQ_PASSWORD=mypass
#           - RABBITMQ_HOST=rabbitmq
#           - REDIS_HOST=redis
#           - FLUENTD_HOST=fluentd
#       command: ["./wait-for-it.sh", "-t", "30", "rabbitmq:5672", "--", "python", "-u", "product_worker.py"]
#   pinkoi_crawler_routine:
#       build:
#           context: .
#           dockerfile: ./side_project/crawler/pinkoi/crawler_routine/Dockerfile
#       environment:
#           - POSTGRES_DB=pinkoi_db
#           - POSTGRES_USER=admin
#           - POSTGRES_PASSWORD=mypass
#           - POSTGRES_HOST=postgres
#           - POSTGRES_PORT=5432  
#           - RABBITMQ_USER=admin
#           - RABBITMQ_PASSWORD=mypass
#           - RABBITMQ_HOST=rabbitmq
#   pinkoi_product_worker:
#       build:
#           context: .
#           dockerfile: ./side_project/crawler/pinkoi/product_worker/Dockerfile
#       deploy:
#           replicas: 30
#       depends_on:
#           - rabbitmq
#           - fluentd
#       environment:
#           - RABBITMQ_USER=admin
#           - RABBITMQ_PASSWORD=mypass
#           - RABBITMQ_HOST=rabbitmq
#           - REDIS_HOST=redis
#           - FLUENTD_HOST=fluentd
#       command: ["./wait-for-it.sh", "-t", "30", "rabbitmq:5672", "--", "python", "-u", "product_worker.py"]
    

volumes:
    postgres:
    rabbitmq:
    redis:
    fluentd:
