version: '3.5'
services:
    rabbitmq-server:
        hostname: rabbitmq-server
        image: rabbitmq:latest
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5672:5672"
        labels:
            NAME: "rabbitmq-server"

    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: 'mypass'
            MYSQL_ROOT_PASSWORD: 'mypass'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - "3306:3306"
        volumes:
            - mydb:/var/lib/mysql

    category_receiver:
        build: .
        depends_on:
            - rabbitmq-server
       #links:
       #    - rabbitmq-server
        environment:
            RABBIT_HOST: rabbitmq-server
        command: ["./wait-for-it.sh", "rabbitmq-server:5672", "--", "python", "-u", "category_worker.py"]

volumes:
    mydb:
