version: '3.7'
services:
    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq:latest
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5672:5672"
        labels:
            NAME: "rabbitmq"
        volumes:
            - rabbitmq:/var/lib/rabbitmq
            - rabbitmq-logs:/var/log/rabbitmq

    mysql:
        image: mysql:5.7
        hostname: mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: 'mypass'
            MYSQL_ROOT_PASSWORD: 'mypass'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - "3306:3306"
        volumes:
            - mysql:/var/lib/mysql


    fluentd:
        build:
            context: .
            dockerfile: src/fluentd/Dockerfile
        volumes:
            - fluentd-conf:/fluentd/etc
        ports:
            - "9880:9880"
        depends_on:
            - mysql
    
    redis:
        image: redis:alpine
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis:/var/lib/redis
    
    category_worker:
        build:
            context: .
            dockerfile: src/category_worker/Dockerfile
        depends_on:
            - rabbitmq
       #links:
       #    - rabbitmq-server
        environment:
            RABBIT_HOST: rabbitmq
            REDIS_HOST: redis
        command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "python", "-u", "category_worker.py"]
    
    worker:
        build:
            context: .
            dockerfile: src/worker/Dockerfile
        depends_on:
            - rabbitmq
            - fluentd
        environment:
            RABBIT_HOST: rabbitmq
            REDIS_HOST: redis
            FLUENTD_HOST: fluentd
        command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "python", "-u", "worker.py"]

volumes:
    rabbitmq:
    rabbitmq-logs:
    mysql:
    fluentd-conf:
    redis:
