version: '3'
services:
    fluentd:
        build: ./conf/fluentd
        ports:
            - 9880:9880
          #      - 24224:24224/udp

              #volumes:

 #minio:
 #  image: minio/minio:RELEASE.2019-10-12T01-39-57Z
 #  volumes:
 #    - minio:/data
 #  ports:
 #    - 9000:9000
 #  environment:
 #    MINIO_ACCESS_KEY: minio
 #    MINIO_SECRET_KEY: minio123
 #  command: server /data
 #  healthcheck:
 #    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
 #    interval: 30s
 #    timeout: 20s
 #    retries: 3
