apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  labels:
    app: fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      imagePullSecrets:
      - name: gitlab-auth
      containers:
      - image: registry.gitlab.com/fevemania/shopee_side_project/fluentd:v0.0.2
        name: fluentd
        ports:
        - containerPort: 9880
