apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-data
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  storageClassName: mysql-data
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
