apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-data
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/postgres"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  storageClassName: postgres-data
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
