apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: db
        - name: POSTGRES_PASSWORD
          value: mypass
        - name: POSTGRES_USER
          value: admin
        image: postgres
        name: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres
      hostname: postgres
      volumes:
      - name: postgres
        persistentVolumeClaim:
          claimName: postgres
